###############################################################
# Author(s):
#     Juhapekka Piiroinen <juhapekka.piiroinen@csc.fi>
#
# License: MIT
#
# (C) 2019 Copyright CSC – IT CENTER FOR SCIENCE LTD.
# All Rights Reserved.
###############################################################
---
- name: "Setup httpd/apache2"
  include_tasks: apache2.yml

- name: "Setup letsencrypt"
  include_tasks: letsencrypt.yml

- name: "Configure apache2"
  include_tasks: apache2-conf.yml
