###############################################################
# Author(s):
#     Juhapekka Piiroinen <juhapekka.piiroinen@csc.fi>
#
# License: MIT
#
# (C) 2019 Copyright CSC – IT CENTER FOR SCIENCE LTD.
# All Rights Reserved.
###############################################################
---
- name: Docker-compose | Install
  shell: pip install docker-compose six>=1.11.0
  become: yes

- name: Docker-compose | Try to use
  shell: docker-compose version
