###############################################################
# This is the MAIN ansible file to run automated
# cPouta Security Group configuration for a project.
#
# Author(s):
#     Juhapekka Piiroinen <juhapekka.piiroinen@csc.fi>
#
# License: MIT
#
# (C) 2019 Copyright CSC – IT CENTER FOR SCIENCE LTD.
# All Rights Reserved.
###############################################################
---
- name: Enable cPouta Project with Security Groups
  with_items: "{{ security_groups | dict2items }}"
  loop_control:
    loop_var: security_group
  include_tasks: task-create-security-group.yml
